# Generated by Django 5.1 on 2024-09-06 18:19

from django.db import migrations
from users.models import User


def create_test_data(apps, schema_editor):

    User.objects.create_user(email='1@mail.ru', password='pass1')
    User.objects.create_user(email='2@mail.ru', password='pass2')
    User.objects.create_user(email='3@mail.ru', password='pass3')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_test_data)
    ]
